// app/layout.tsx
import type { Metadata } from "next";
// Removendo Geist e Geist_Mono, adicionando Poppins
import { Poppins } from "next/font/google"; 
import "./globals.css";

// 1. Definição da fonte Poppins com os pesos comuns
const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ['400', '600', '700', '800'], // Pesos comuns usados no projeto (normal, semibold, bold, extrabold)
  subsets: ["latin"],
});

// A Geist Mono é mantida se precisar dela, senão pode ser removida
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Aplicamos a variável da Poppins na tag <body> */}
      <body
        className={`${poppins.variable} antialiased`} 
      >
        {children}
      </body>
    </html>
  );
}